#The name of the world where your minimap is
mapworld: 'NONE'
leaveworld: 'NONE'
#The block that you want to represent a location that the player has discovered
changeblock: 'gold_block'
#The scale of the normal world to the map world. I.E. 2 would mean one block
#in the normal world is 1 block in the map world.
#Similarly, 0.5 means that one block in the map world is 2 blocks in the normal world
scale: 16
#The bounding box that you want players to be able to access the map from (in the normal world)
#Player who enter the map from outside of this area will be placed at the part of the edge closest to them
bounding-box:
  pos1:
    x: 100
    z: 100
  pos2:
    x: -100
    z: -100

#The y-value of the map in the map world
#Players will spawn 1 block above this
#(You can change this manually if you want players to spawn at a different height in the world)
map-y: 4

#Locations you've saved
locations:
  example:
    destination:
      x: 0
      y: 0
      z: 0
      world: 'world'
    map-pos:
      x: 0
      y: 0
      z: 0
  example2:
    destination:
      x: 0
      y: 0
      z: 0
      world: 'world'
    map-pos:
      x: 0
      y: 0
      z: 0